"""Rebuild the control skeleton inside Blender from the tool-neutral procedural definition.

Run from a shell (Blender is not required for the GLB export path; this is only for the archival
``.blend`` and for any downstream STEP conversion)::

    blender --background --python cad/procedural/build_in_blender.py -- \
        --input cad/procedural/control_skeleton_geometry.json \
        --output cad/procedural/control_skeleton.blend

Design notes
------------
* The JSON is generated by ``scripts/build_control_skeleton.py`` and contains no dimensions of its
  own; every number in it traces back to GEOMETRY-CONTROL.md.
* Authoring units are meters in a Z-up frame, which matches Blender's default frame, so no rotation
  is applied here.
* Part metadata is written to Blender custom properties so that the ``.blend`` carries the same
  metadata contract as the GLB.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import bpy
except ImportError:  # pragma: no cover - the module is only importable inside Blender
    bpy = None

METADATA_KEYS = (
    "part_id",
    "system",
    "subsystem",
    "source_basis",
    "confidence",
    "prototype_units",
    "ho_scale_units",
    "notes",
    "scale",
    "last_modified_by_agent",
    "review_status",
    "control_refs",
    "open_questions",
)


def parse_args(argv: list[str]) -> argparse.Namespace:
    if "--" in argv:
        argv = argv[argv.index("--") + 1 :]
    parser = argparse.ArgumentParser(description="Rebuild the control skeleton in Blender.")
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=None)
    return parser.parse_args(argv)


def ensure_collection(name: str):
    if name in bpy.data.collections:
        return bpy.data.collections[name]
    collection = bpy.data.collections.new(name)
    bpy.context.scene.collection.children.link(collection)
    return collection


def box_geometry(bmin, bmax):
    x0, y0, z0 = bmin
    x1, y1, z1 = bmax
    verts = [
        (x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
        (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1),
    ]
    faces = [
        (0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4),
        (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7),
    ]
    return verts, [], faces


def part_mesh(part: dict):
    """Merge a part's primitives into a single Blender mesh (edges for curves, faces for solids)."""
    verts: list[tuple[float, float, float]] = []
    edges: list[tuple[int, int]] = []
    faces: list[tuple[int, ...]] = []
    for prim in part["geometry"]:
        kind = prim["kind"]
        base = len(verts)
        if kind == "box":
            b_verts, _, b_faces = box_geometry(prim["min"], prim["max"])
            verts.extend(b_verts)
            faces.extend(tuple(base + i for i in face) for face in b_faces)
        elif kind == "quad":
            verts.extend(tuple(c) for c in prim["corners"])
            faces.append(tuple(base + i for i in range(4)))
        elif kind == "polyline":
            points = prim["points"]
            verts.extend(tuple(p) for p in points)
            edges.extend((base + i, base + i + 1) for i in range(len(points) - 1))
        elif kind == "lines":
            for start, end in prim["segments"]:
                index = len(verts)
                verts.append(tuple(start))
                verts.append(tuple(end))
                edges.append((index, index + 1))
        else:
            raise ValueError(f"unknown geometry kind {kind!r}")
    return verts, edges, faces


def main(argv: list[str]) -> int:
    if bpy is None:
        print("This script must be run inside Blender:")
        print("  blender --background --python cad/procedural/build_in_blender.py -- --input ...")
        return 2

    args = parse_args(argv)
    document = json.loads(Path(args.input).read_text(encoding="utf-8"))

    bpy.ops.wm.read_factory_settings(use_empty=True)
    bpy.context.scene.unit_settings.system = "METRIC"
    bpy.context.scene.unit_settings.length_unit = "METERS"

    for part in document["parts"]:
        verts, edges, faces = part_mesh(part)
        mesh = bpy.data.meshes.new(f"{part['part_id']}_mesh")
        mesh.from_pydata(verts, edges, faces)
        mesh.update()
        obj = bpy.data.objects.new(part["part_id"], mesh)
        for key in METADATA_KEYS:
            value = part.get(key)
            obj[key] = json.dumps(value) if isinstance(value, (list, dict)) else value
        collection_name = part["system"] if not part.get("subsystem") else f"{part['system']}.{part['subsystem']}"
        ensure_collection(collection_name).objects.link(obj)

    print(f"rebuilt {len(document['parts'])} parts from {args.input}")
    print(f"control document sha256 = {document['control_document']['sha256'][:12]}")

    if args.output:
        output = Path(args.output).resolve()
        output.parent.mkdir(parents=True, exist_ok=True)
        bpy.ops.wm.save_as_mainfile(filepath=str(output))
        print(f"saved {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
